# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 431))
        self.groupBox.setObjectName("groupBox")
        self.Confirm = QtWidgets.QPushButton(self.groupBox)
        self.Confirm.setGeometry(QtCore.QRect(180, 390, 151, 31))
        self.Confirm.setObjectName("Confirm")
        self.Cansel = QtWidgets.QPushButton(self.groupBox)
        self.Cansel.setGeometry(QtCore.QRect(10, 390, 161, 31))
        self.Cansel.setObjectName("Cansel")
        self.FullName = QtWidgets.QLineEdit(self.groupBox)
        self.FullName.setGeometry(QtCore.QRect(10, 20, 321, 31))
        self.FullName.setText("")
        self.FullName.setObjectName("FullName")
        self.PhoneNumber = QtWidgets.QLineEdit(self.groupBox)
        self.PhoneNumber.setGeometry(QtCore.QRect(10, 70, 321, 31))
        self.PhoneNumber.setToolTip("")
        self.PhoneNumber.setStatusTip("")
        self.PhoneNumber.setText("")
        self.PhoneNumber.setObjectName("PhoneNumber")
        self.Email = QtWidgets.QLineEdit(self.groupBox)
        self.Email.setGeometry(QtCore.QRect(10, 120, 321, 31))
        self.Email.setObjectName("Email")
        self.sum_ = QtWidgets.QLineEdit(self.groupBox)
        self.sum_.setGeometry(QtCore.QRect(10, 170, 321, 31))
        self.sum_.setObjectName("sum_")
        self.Comments = QtWidgets.QTextEdit(self.groupBox)
        self.Comments.setGeometry(QtCore.QRect(10, 210, 321, 131))
        self.Comments.setObjectName("Comments")
        self.Resalt = QtWidgets.QLabel(self.groupBox)
        self.Resalt.setGeometry(QtCore.QRect(20, 350, 311, 20))
        self.Resalt.setText("")
        self.Resalt.setObjectName("Resalt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Подарункові сертифікати"))
        self.Confirm.setText(_translate("MainWindow", "ПІДТВЕРДИТИ"))
        self.Cansel.setText(_translate("MainWindow", "ВІДМІНИТИ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
